server:
  port: 8082

spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb+srv://kobara_db_user:wow12345@cluster0.xxu3l1m.mongodb.net/activityfitness?retryWrites=true&w=majority
