server:
  port: 8080

spring:
  application:
    name: userservice

  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Emko5733
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false  # explicitly disable to avoid warning

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.f.userservice: DEBUG
